### ISSUE TITLE
XSRF verification not passing

### ISSUE THREAD

**Issue by phillipdavidstearns** [chaaaaaarlie/resistance#1]
I've modified your code to more closely match this survey:
https://gop.com/president-trump-first-50-survey/
, but the CSRF verification isn't passing.

```
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>
```

[signmeup_50.txt](https://github.com/chaaaaaarlie/resistance/files/850193/signmeup_50.txt)

**Comment by chaaaaaarlie** [comment]
Hi Phillip, 

Can you issue a pull request so I can review your changes? I've been working on some locally and would like to compare notes.

**Comment by phillipdavidstearns** [comment]
looks like all the surveys are offline as of this post. [here's where they used to live...](https://gop.com/get-involved/?selected_tab=surveys)

BTWs they're using [nginx](https://www.nginx.com/)

**Comment by chaaaaaarlie** [comment]
So, I'm by no means a hacker, or even a web guy - I'm backend/big data. My best guess is that they're blocking repeat submissions within a certain time frame from the same IP. Limiting my posts to once per 20 seconds seems to have remedied it. This isn't ideal, but I'm not sure if I have the expertise to propose a better solution. It's still 10k bogus posts per user per day, so the ultimate solution may just be to get more users.

BTdubs, having googled you, I'm totally buying one of your throws for my friend's birthday =)
